name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/app/dbsf-educator-forum-api/
            git pull origin master
            /home/${{ secrets.SSH_USER }}/.nvm/versions/node/v14.18.1/bin/npm install
            /home/${{ secrets.SSH_USER }}/.nvm/versions/node/v14.18.1/bin/npm run migrate up
            /home/${{ secrets.SSH_USER }}/.nvm/versions/node/v14.18.1/bin/pm2 restart dbsf-educator-forum-api
