name: Continuous Integration

on:
  pull_request:
    branches:
      - master
jobs:
  runner-job:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: testing
          POSTGRES_PASSWORD: testing
          POSTGRES_DB: forumapi_test

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install migrate and test
        run: |
          npm install
          npm run migrate up
          npm run test
        env:
          CI: true
          PGHOST_TEST: localhost
          PGUSER_TEST: testing
          PGDATABASE_TEST: forumapi_test
          PGPASSWORD_TEST: testing
          PGPORT_TEST: 5432
          PGHOST: localhost
          PGUSER: testing
          PGDATABASE: forumapi_test
          PGPASSWORD: testing
          PGPORT: 5432
          ACCESS_TOKEN_KEY: secret
          REFRESH_TOKEN_KEY: secret
          ACCESS_TOKEN_AGE: 3600
          HOST: localhost
          PORT: 5000
