name: Continuous Integration

on:
  pull_request:
    branches:
      - master
jobs:
  automation-test-job:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: testing
          POSTGRES_PASSWORD: testing
          POSTGRES_DB: forumapi_test

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: git checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: npm install migrate and test
        run: |
          npm install
          npm run migrate up
          npm run test
        env:
          CI: true
          PGHOST_TEST: localhost
          PGUSER_TEST: testing
          PGDATABASE_TEST: forumapi_test
          PGPASSWORD_TEST: testing
          PGPORT_TEST: 5432
          PGHOST: localhost
          PGUSER: testing
          PGDATABASE: forumapi_test
          PGPASSWORD: testing
          PGPORT: 5432
          ACCESS_TOKEN_KEY: access_token_key
          REFRESH_TOKEN_KEY: refresh_token_key
          ACCESS_TOKEN_AGE: 3600
          HOST: localhost
          PORT: 5000
